package:
  name: cross-binutils-stage1
  version: 2.39
  epoch: 0
  description: "the GNU binary utilities (cross compilation)"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: GPL-3.0-or-later
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
    packages:
      - alpine-baselayout-data
      - busybox
      - build-base
      - scanelf
      - ssl_client
      - ca-certificates-bundle
      - texinfo

pipeline:
  - uses: fetch
    with:
      uri: https://ftp.gnu.org/gnu/binutils/binutils-${{package.version}}.tar.gz
      expected-sha256: d12ea6f239f1ffe3533ea11ad6e224ffcb89eb5d01bbea589e9158780fa11f10
  - name: 'Configure binutils'
    runs: |
      ./configure \
        --prefix=/usr \
        --libdir=/lib \
        --target=$(uname -m)-pc-linux-gnu \
        --disable-nls \
        --disable-werror \
        --with-sysroot=/usr/$(uname -m)-pc-linux-gnu
  - uses: autoconf/make
  - uses: autoconf/make-install
  - name: 'Clean up documentation'
    runs: |
      rm -rf ${{targets.destdir}}/usr/share/info
  - uses: strip
