package:
  name: cross-binutils-stage1
  version: 2.39
  epoch: 0
  description: "the GNU binary utilities (cross compilation)"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: GPL-3.0-or-later
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
    packages:
      - alpine-baselayout-data
      - busybox
      - build-base
      - scanelf
      - ssl_client
      - ca-certificates-bundle
      - texinfo
      - isl-dev

pipeline:
  - uses: fetch
    with:
      uri: https://ftp.gnu.org/gnu/binutils/binutils-${{package.version}}.tar.gz
      expected-sha256: d12ea6f239f1ffe3533ea11ad6e224ffcb89eb5d01bbea589e9158780fa11f10
  - name: 'Configure binutils'
    runs: |
      ./configure \
        --prefix=/usr \
        --target=${{host.triplet.gnu}} \
        --disable-nls \
        --disable-werror \
        --disable-multilib \
        --disable-gprofng \
        --with-sysroot=/usr/${{host.triplet.gnu}}
  - uses: autoconf/make
  - uses: autoconf/make-install
  - name: 'Add target aliases'
    runs: |
      BASE="${{targets.destdir}}"/usr/libexec/gcc/${{host.triplet.gnu}}

      mkdir -p $BASE
      ln -f ${{targets.destdir}}/usr/bin/${{host.triplet.gnu}}-as $BASE/as
      ln -f ${{targets.destdir}}/usr/bin/${{host.triplet.gnu}}-ld $BASE/ld
  - name: 'Clean up BFD plugins'
    runs: |
      rm -rf ${{targets.destdir}}/usr/lib/bfd-plugins
  - name: 'Clean up documentation'
    runs: |
      rm -rf ${{targets.destdir}}/usr/share/info
  - uses: strip
